version: '3.7'

services:
  backend:
    image: thecodeisalreadydeployed/backend:dev
    build: .
    restart: unless-stopped
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: codedeploy
      DATABASE_PORT: "5432"
    ports:
      - 3000:3000
