apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codedeploy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codedeploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codedeploy
subjects:
- kind: ServiceAccount
  name: codedeploy
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codedeploy
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: codedeploy
  name: codedeploy
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    app: codedeploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codedeploy
  name: codedeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codedeploy
  strategy: {}
  template:
    metadata:
      labels:
        app: codedeploy
    spec:
      restartPolicy: Never
      serviceAccountName: codedeploy
      containers:
        - image: ko://github.com/thecodeisalreadydeployed
          name: backend
          ports:
            - containerPort: 3000
              name: http
          resources: {}
          env:
            - name: DATABASE_HOST
              value: postgres.default.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: codedeploy
            - name: APP_ENV
              value: TEST_KUBERNETES
            - name: GITSERVER_HOST
              value: git://gitserver.default.svc.cluster.local:9418
            - name: USERSPACE_REPOSITORY
              value: /etc/gitserver/userspace
          volumeMounts:
            - mountPath: /etc/gitserver
              name: codedeploy-pv
      volumes:
        - name: codedeploy-pv
          persistentVolumeClaim:
            claimName: codedeploy-pvc
status: {}
