apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.2/manifests/install.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: --disable-auth
    target:
      group: apps
      version: v1
      name: argocd-server
      kind: Deployment
