apiVersion: v1
kind: Service
metadata:
  labels:
    app: codedeploy
  name: codedeploy
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    app: codedeploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codedeploy
  name: codedeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codedeploy
  strategy: {}
  template:
    metadata:
      labels:
        app: codedeploy
    spec:
      containers:
        - image: thecodeisalreadydeployed/backend:dev
          name: backend
          ports:
            - containerPort: 3000
              name: http
          resources: {}
status: {}
