apiVersion: v1
kind: Service
metadata:
  labels:
    app: codedeploy
  name: codedeploy
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    app: codedeploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: codedeploy
  name: codedeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codedeploy
  strategy: {}
  template:
    metadata:
      labels:
        app: codedeploy
    spec:
      containers:
        - image: ko://github.com/thecodeisalreadydeployed
          name: backend
          ports:
            - containerPort: 3000
              name: http
          resources: {}
          env:
            - name: DATABASE_HOST
              value: postgres.default.svc.cluster.local
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: codedeploy
status: {}
