package constant

type ConfigurationConstant string

const USERSPACE_REPOSITORY = "USERSPACE_REPOSITORY"
const ARGOCD_SERVER_HOST = "ARGOCD_SERVER_HOST"
const AUTH0_DOMAIN = "AUTH0_DOMAIN"
const AUTH0_AUDIENCE = "AUTH0_AUDIENCE"
const DATABASE_HOST = "DATABASE_HOST"
const DATABASE_USERNAME = "DATABASE_USERNAME"
const DATABASE_PASSWORD = "DATABASE_PASSWORD"
const DATABASE_NAME = "DATABASE_NAME"
const DATABASE_PORT = "DATABASE_PORT"
const GITSERVER_HOST = "GITSERVER_HOST"
