apiVersion: v1
kind: Service
metadata:
  name: gitserver
  namespace: default
spec:
  selector:
    app: gitserver
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: git
    port: 9418
