name: build/imagebuilder
on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "imagebuilder/**"
      - "logexporter/**"
      - ".github/workflows/build-imagebuilder.yaml"
    branches:
      - main
      - dev/imagebuilder
      - dev/imagebuilder-docker
jobs:
  test:
    runs-on: ubuntu-20.04
    concurrency:
      group: build/imagebuilder:${{ github.head_ref }}
      cancel-in-progress: true
    env:
      SHA7: ${GITHUB_SHA::7}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o logexporter-linux-amd64 -ldflags '-w -s' ./logexporter
      - run: ls
      - run: ls ./logexporter
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: metadata-action
        with:
          images: |
            ghcr.io/thecodeisalreadydeployed/imagebuilder
          tags: |
            type=sha
            type=raw,value=latest
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: imagebuilder/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata-action.outputs.tags }}
          labels: ${{ steps.metadata-action.outputs.labels }}
