name: build/imagebuilder
on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "imagebuilder/**"
      - "logexporter/**"
      - ".github/workflows/build-imagebuilder.yaml"
    branches:
      - dev/imagebuilder
      - dev/imagebuilder-docker
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      SHA7: ${GITHUB_SHA::7}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: GOOS=linux GOARCH=amd64 go build -o logexporter-linux-amd64 ./logexporter
      - run: ls
      - run: ls ./logexporter
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: imagebuilder/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            thecodeisalreadydeployed/imagebuilder:latest
            thecodeisalreadydeployed/imagebuilder:${{ env.SHA7 }}
            ghcr.io/thecodeisalreadydeployed/imagebuilder:latest
            ghcr.io/thecodeisalreadydeployed/imagebuilder:${{ env.SHA7 }}
