name: build/imagebuilder
on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "imagebuilder/**"
      - "logexporter/**"
      - ".github/workflows/build-imagebuilder.yaml"
    branches:
      - dev/imagebuilder
      - dev/imagebuilder-docker
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - run: GOOS=linux GOARCH=amd64 go build ./logexporter -o logexporter-linux-amd64
      - run: ls
      - run: ls ./logexporter
