name: 'build: metadataserver'
on:
  push:
    branches:
      - main
      - ci/senior-project
jobs:
  test:
    runs-on: ubuntu-20.04
    concurrency:
      group: build/metadataserver:${{ github.head_ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: metadata-action
        with:
          images: |
            ghcr.io/thecodeisalreadydeployed/metadataserver
          tags: |
            type=sha
            type=raw,value=latest
      - uses: docker/build-push-action@v2
        with:
          context: ./metadataserver
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.metadata-action.outputs.tags }}
          labels: ${{ steps.metadata-action.outputs.labels }}
