name: dev/gitserver
on:
  push:
    paths:
      - "dev/gitserver/**"
      - ".github/workflows/dev-gitserver.yaml"
    branches:
      - dev/gitserver
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd dev/gitserver && docker build -t thecodeisalreadydeployed/gitserver:dev .
      - run: mkdir _tmp && mkdir _ssh
      - run: |
          docker run -d \
            -p 2222:22 \
            --name gitserver \
            -v $(pwd)/_tmp/keys:/__w/keys \
            -v $(pwd)/_tmp/repos:/__w/repos \
            thecodeisalreadydeployed/gitserver:dev
      - run: ssh-keygen -t ed25519 -a 100 -f $(pwd)/_ssh/id_rsa -q -N "" -m pem
      - run: ls _ssh/
      - run: sudo cp _ssh/id_rsa.pub _tmp/keys
      - id: private-key
        run: |
          echo 'PRIVATE_KEY<<EOF' >> $GITHUB_ENV
          cat _ssh/id_rsa >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: docker restart gitserver
      - run: |
          cd _tmp/repos
          sudo mkdir userspace
          cd userspace
          sudo git init --shared=true
          sudo touch .codedeploy
          sudo git add .codedeploy
          sudo git commit -m ".codedeploy: init"
      - run: docker logs gitserver
      - run: docker ps
      - run: docker exec gitserver ls /__w/keys
      - run: docker exec gitserver ls /__w/repos
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ env.PRIVATE_KEY }}
      - run: git clone ssh://codedeploy@localhost:2222/__w/repos/userspace.git
      - run: ls
