name: dev/gitserver
on:
  push:
    paths:
      - "dev/gitserver/**"
      - ".github/workflows/dev-gitserver.yaml"
    branches:
      - dev/gitserver
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: cd dev/gitserver && docker build -t thecodeisalreadydeployed/gitserver:dev .
      - run: |
          mkdir tmp
          docker run -d \
            -p 2222:22 \
            --name gitserver \
            -v $(pwd)/tmp/keys:/__w/keys \
            -v $(pwd)/tmp/repos:/__w/repos \
            thecodeisalreadydeployed/gitserver:dev
