name: golangci-lint
on:
  push:
jobs:
  golangci-lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v2.5.2
