name: dev/integration-tests
on:
  push:
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make kind
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: thecodeisalreadydeployed/backend:dev
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - run: kind load docker-image thecodeisalreadydeployed/backend:dev
      - run: kubectl -n argocd wait deploy/argocd-server --for condition=available --timeout 5m
        timeout-minutes: 5
      - run: kubectl -n argocd port-forward svc/argocd-server 8080:443 &
      - run: |
          ARGOCD_HOST=localhost:8080
          ARGOCD_SERVER=http://$ARGOCD_HOST
          ARGOCD_USERNAME=admin
          ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          sudo curl -k -sSL -o /usr/local/bin/argocd "$ARGOCD_SERVER/download/argocd-linux-amd64"
          sudo chmod +x /usr/local/bin/argocd
          argocd login "$ARGOCD_HOST" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --insecure
      - run: argocd version
      - run: argocd app sync codedeploy
      - run: argocd app wait codedeploy --timeout 300
        timeout-minutes: 5
      - run: |
          kubectl -n default wait deploy/gitserver --for condition=available --timeout 5m
          kubectl -n kubegres-system wait deploy/kubegres-controller-manager --for condition=available --timeout 5m
        timeout-minutes: 5
      - run: |
          kubectl -n default wait pod/postgres-1-0 --for condition=Ready --timeout 5m
        timeout-minutes: 5
      - run: |
          kubectl -n default apply -f hack/ci/backend.yaml
      - run: |
          kubectl -n default wait deploy/codedeploy --for condition=available --timeout 5m
        timeout-minutes: 5
      - run: kubectl -n default port-forward svc/codedeploy 3000:3000 &
      - run: make e2e
