name: dev/integration-tests
on:
  push:
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: codedeploy
          POSTGRES_USER: user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - run: sh hack/0-kind-create-cluster.sh
      - run: docker build -t thecodeisalreadydeployed/backend:dev . --push
      - run: kind load docker-image thecodeisalreadydeployed/backend:dev
      - run: sh hack/1-kubectl-apply-argocd.sh
      - run: kubectl -n argocd wait deploy/argocd-server --for condition=available
        timeout-minutes: 5
