name: dev/integration-tests
on:
  push:
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    container: node:14
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: codedeploy
          POSTGRES_USER: user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
