name: dev/integration-tests
on:
  push:
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sh hack/0-kind-create-cluster.sh
      - run: docker build -t thecodeisalreadydeployed/backend:dev .
      - run: kind load docker-image thecodeisalreadydeployed/backend:dev
      - run: sh hack/1-kubectl-apply-argocd.sh
      - run: kubectl -n argocd wait deploy/argocd-server --for condition=available
        timeout-minutes: 5
      - run: kubectl -n argocd port-forward svc/argocd-server -n argocd 8080:443
      - run: ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
