name: dev/integration-tests
on:
  push:
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sh hack/0-kind-create-cluster.sh
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: thecodeisalreadydeployed/backend:dev
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: kind load docker-image thecodeisalreadydeployed/backend:dev
      - run: sh hack/1-kubectl-apply-argocd.sh
      - run: kubectl -n argocd wait deploy/argocd-server --for condition=available --timeout 5m
        timeout-minutes: 5
      - run: kubectl -n argocd port-forward svc/argocd-server -n argocd 8080:443 &
      - run: |
          ARGOCD_HOST=localhost:8080
          ARGOCD_SERVER=http://$ARGOCD_HOST
          ARGOCD_USERNAME=admin
          ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          sudo curl -k -sSL -o /usr/local/bin/argocd "$ARGOCD_SERVER/download/argocd-linux-amd64"
          sudo chmod +x /usr/local/bin/argocd
          argocd login "$ARGOCD_HOST" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --insecure
      - run: argocd version
