name: 'test: unit'
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        pkg: [
          'gitgateway/v2',
          'repositoryobserver',
          'datastore',
          'datamodel',
          'gitopscontroller',
          'gitapi/github'
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
      - run: go test -v ./${{ matrix.pkg }}
